[package]
name = "twitch-dl-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
regex = "1.11.1"
reqwest = "0.12.20"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.45.1"
urlencoding = "2.1.3"
